services:
 
  ffs:
    build: ./fss
    volumes:
      - ./mnt/video:/app/data
    ports:
      - "8000:8000"

  db:
    image: mysql:8.0
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: rootpass
      MYSQL_USER: chud
      MYSQL_PASSWORD: son
      MYSQL_DATABASE: video
    ports:
      - "3306:3306"
    volumes:
      - my-db:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
volumes:
  my-db:
  
web-app:
  build: ./web-app
  ports:
    - "5000:5000"
  environment:
    - DB_SERVICE_URL=http://db:3306
    - FILESYSTEM_SERVICE_URL=http://ffs:8000
  depends_on:
    - db
    - ffs

